image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      cp config/database.example.yml config/database.yml &&
      createuser -s postgres &&
      (redis-server &) &&
      bundle install --without production &&
      rails db:setup &&
      rails db:migrate &&
      bundle exec rake sunspot:solr:start
    command: >
      rails db:migrate &&
      bundle exec rails
github:
    prebuilds:
        pullRequestsFromForks: true
