image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      cp config/database.example.yml config/database.yml &&
      createuser -s postgres &&
      bundle install --without production &&
      bundle exec rake sunspot:solr:start &&
      rails db:setup
    command: >
      bin/setup &&
      rails s
github:
    prebuilds:
        pullRequestsFromForks: true
